# NOTE: while mentioning Google cloud storage paths, mention full path starting from 'gs://'
train_params:
  batch_size: 2048
  num_epochs: 10
  steps_per_epoch: 1700
  data_dir: 'gs://text-analysis-323506/train_data/'
  output_dir: 'gs://text-analysis-323506/train_results/'

  # Comment/remove a callback section to disable it
  callbacks:
    # Tensorboard callback.
    TensorBoard:
      log_dir: 'gs://text-analysis-323506/train_results/tensorboard'

    # Model checkpoint callback.
    ModelCheckpoint:
      # Only mention the model name here, a folder called 'checkpoints' containing checkpoints will be created in
      # 'output_dir' specified above in 'train_params'
      filepath: 'model.{epoch:02d}-{val_loss:.2f}.hdf5'
      monitor: 'val_accuracy'
      save_freq: 'epoch'
      verbose: 1
      period: 1
      save_best_only: False
      save_weights_only: True

    # Early stopping callback.
    EarlyStopping:
      monitor: 'val_accuracy'
      mode: 'min'
      verbose: 1
      patience: 5

    # Csv logger callback.
    CSVLogger:
      # Only mention csv file name here, This csb file will be dumped to  'output_dir' specified above in 'train_params' 
      filename: 'train_logs.csv'
      separator: ','
      append: False

predict_params:
  model_path: 'gs://text-analysis-323506/train_results/trained_model/2021_08_01-10:07:06/CNN_Amazon_Reviews_Analysis.hdf5'
  data_path: 'gs://text-analysis-323506/test_images'
  results_path: 'gs://text-analysis-323506/test_results/CNN_test_results.csv'
  tokenizer_path: 'gs://text-analysis-323506/train_results_CNN/CNN_2021_09_25-11:20:36/parser_output/tokenizer.pickle'

model_params:
  # Three types of models are available. 'CNN', 'LSTM' and 'Hybrid'. Hybrid model is a mixture of Conv1D layers and
  # LSTM cells.
  # During prediction, 'model' field should be set to type of model defined in 'model_path' field of 'predict_params'
  model: 'CNN'
  optimizer: 'adam'
  loss: "binary_crossentropy"
  metrics: ["accuracy"]
  embedding_dim: 200
